[package]
name = "rrule_codec_rs"
version = "0.1.4"
authors = ["Chris Hopkins"]
edition = "2024"

[lib]
name = "rrule_codec_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.0"
rrule = "0.13.0"
chrono = "0.4.19"
chrono-tz = "0.6.1"