[package]
name = "exdateutil_rrule"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "exdateutil_rrule"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.0"
rrule = "0.13.0"
chrono = "0.4.19"
chrono-tz = "0.6.1"